# Generated by Django 5.1 on 2024-09-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='example-Slug', unique=True),
            preserve_default=False,
        ),
    ]
