# Generated by Django 5.1 on 2024-09-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('year', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=4)),
                ('department', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Electrical Engineering', 'Electrical Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Chemical Engineering', 'Chemical Engineering')], max_length=50)),
            ],
        ),
    ]
