# Generated by Django 5.1 on 2024-09-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_registration_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='full_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_login',
        ),
    ]
