# Generated by Django 5.1 on 2024-09-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_registration_last_login_alter_registration_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['username'], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='pincode',
            new_name='pin',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='registration',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='department',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('ee', 'Electrical Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering'), ('bt', 'Biotechnology'), ('che', 'Chemical Engineering')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registration',
            name='year',
            field=models.CharField(choices=[('1st', '1st Year'), ('2nd', '2nd Year'), ('3rd', '3rd Year'), ('4th', '4th Year')], max_length=10),
        ),
    ]
